package com.topout.kmp.utils.extensions

import com.topout.kmp.Track_points         // generated by SQLDelight
import com.topout.kmp.models.AlertType
import com.topout.kmp.models.LatLng
import com.topout.kmp.models.TrackPoint

/* DB ➜ domain  */
fun Track_points.toTrackPoint(): TrackPoint = TrackPoint(
    id             = id,
    sessionId      = sessionId,
    timestamp      = ts,
    latitude       = lat,
    longitude      = lon,
    altitude       = altitude,
    accelerationX  = accelX?.toFloat(),
    accelerationY  = accelY?.toFloat(),
    accelerationZ  = accelZ?.toFloat(),
    gain           = gain ?: 0.0,
    loss           = loss ?: 0.0,
    relAltitude    = relAltitude ?: 0.0,
    avgHorizontal  = avgHorizontal ?: 0.0,
    avgVertical    = avgVertical ?: 0.0,
    danger         = danger == 1L,
    alertType      = AlertType.valueOf(alertType ?: "NONE")
)

/* domain ➜ DB  */
fun TrackPoint.toEntity(): Track_points = Track_points(
    id            = id,
    sessionId     = sessionId,
    ts            = timestamp,
    lat           = latitude,
    lon           = longitude,
    altitude      = altitude,
    accelX        = accelerationX?.toDouble(),
    accelY        = accelerationY?.toDouble(),
    accelZ        = accelerationZ?.toDouble(),
    gain          = gain,
    loss          = loss,
    relAltitude   = relAltitude,
    avgHorizontal = avgHorizontal,
    avgVertical   = avgVertical,
    danger        = if (danger) 1L else 0L,
    alertType     = alertType.name
)

fun TrackPoint.latLngOrNull(): LatLng? =
    latitude?.let { lat -> longitude?.let { lon -> LatLng(lat, lon) } }
